[2024-07-25T17:08:43.061+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T17:08:43.070+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.create_dag_run manual__2024-07-25T17:08:41.314134+00:00 [queued]>
[2024-07-25T17:08:43.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.create_dag_run manual__2024-07-25T17:08:41.314134+00:00 [queued]>
[2024-07-25T17:08:43.073+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-25T17:08:43.077+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_dag_run> on 2024-07-25 17:08:41.314134+00:00
[2024-07-25T17:08:43.079+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T17:08:43.080+0000] {standard_task_runner.py:64} INFO - Started process 262 to run task
[2024-07-25T17:08:43.080+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'create_dag_run', 'manual__2024-07-25T17:08:41.314134+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmptl2qyc71']
[2024-07-25T17:08:43.081+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask create_dag_run
[2024-07-25T17:08:43.097+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_dag.create_dag_run manual__2024-07-25T17:08:41.314134+00:00 [running]> on host 199ee4d55a47
[2024-07-25T17:08:43.126+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Pattakit' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='create_dag_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T17:08:41.314134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-25T17:08:41.314134+00:00'
[2024-07-25T17:08:43.127+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T17:08:43.131+0000] {sql.py:282} INFO - Executing: 
            insert into dag_runs (ds, dag_id) values ('2024-07-25', 'postgres_dag');
        
[2024-07-25T17:08:43.134+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-07-25T17:08:43.137+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-07-25T17:08:43.141+0000] {sql.py:495} INFO - Running statement: 
            insert into dag_runs (ds, dag_id) values ('2024-07-25', 'postgres_dag');
        , parameters: None
[2024-07-25T17:08:43.142+0000] {sql.py:504} INFO - Rows affected: 1
[2024-07-25T17:08:43.142+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T17:08:43.145+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_dag_run, run_id=manual__2024-07-25T17:08:41.314134+00:00, execution_date=20240725T170841, start_date=20240725T170843, end_date=20240725T170843
[2024-07-25T17:08:43.180+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T17:08:43.191+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T17:08:43.192+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
