[2024-07-26T06:33:33.603+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-26T06:33:33.617+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 manual__2024-07-26T06:33:33.125589+00:00 [queued]>
[2024-07-26T06:33:33.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 manual__2024-07-26T06:33:33.125589+00:00 [queued]>
[2024-07-26T06:33:33.621+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-26T06:33:33.626+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-07-26 06:33:33.125589+00:00
[2024-07-26T06:33:33.629+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=976) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-26T06:33:33.630+0000] {standard_task_runner.py:64} INFO - Started process 977 to run task
[2024-07-26T06:33:33.630+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '8_postgres_to_s3_dag.py', 'postgres_to_s3', 'manual__2024-07-26T06:33:33.125589+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/8_postgres_to_s3_dag.py', '--cfg-path', '/tmp/tmpbyjmqcb7']
[2024-07-26T06:33:33.631+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask postgres_to_s3
[2024-07-26T06:33:33.651+0000] {task_command.py:426} INFO - Running <TaskInstance: 8_postgres_to_s3_dag.py.postgres_to_s3 manual__2024-07-26T06:33:33.125589+00:00 [running]> on host ecd5bbc03de3
[2024-07-26T06:33:33.683+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='8_postgres_to_s3_dag.py' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-26T06:33:33.125589+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-26T06:33:33.125589+00:00'
[2024-07-26T06:33:33.684+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-26T06:33:33.696+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-07-26T06:33:33.711+0000] {8_postgres_to_s3_dag.py:31} INFO - Saved orders data into text file: get_orders_2024-07-26T06:33:33.125589+00:00.txt
[2024-07-26T06:33:33.712+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-26T06:33:33.713+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-26T06:33:33.732+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=8_postgres_to_s3_dag.py, task_id=postgres_to_s3, run_id=manual__2024-07-26T06:33:33.125589+00:00, execution_date=20240726T063333, start_date=20240726T063333, end_date=20240726T063333
[2024-07-26T06:33:33.774+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-26T06:33:33.782+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-26T06:33:33.782+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
